spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=TRAINBODYBUILDER
spring.datasource.password=Dce81125
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

# Força UTF-8 no request/response
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Garante Jackson como mapper padrão
spring.mvc.converters.preferred-json-mapper=jackson


# não precisa setar o dialect

server.port=8080
springdoc.swagger-ui.path=/swagger-ui/index.html


# mostra o SQL e a validação de schema
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.tool.schema.internal=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
spring.jpa.hibernate.ddl-auto=validate


